version: '3.8'

services:
  backend:
    build: ./backend
    container_name: meal_planner_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
      - ./pdfs:/app/pdfs
    restart: unless-stopped
    networks:
      - meal_planner_network

  frontend:
    build: ./frontend
    container_name: meal_planner_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - meal_planner_network

networks:
  meal_planner_network:
    driver: bridge