version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: meal_planner_chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped
    networks:
      - meal_planner_network

  backend:
    build: ./backend
    container_name: meal_planner_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    volumes:
      - ./backend/data:/app/data
      - ./pdfs:/app/pdfs
    depends_on:
      - chromadb
    restart: unless-stopped
    networks:
      - meal_planner_network

  frontend:
    build: ./frontend
    container_name: meal_planner_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - meal_planner_network

networks:
  meal_planner_network:
    driver: bridge