version: "3.8"

services:
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8001
      - DEBUG=False
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    volumes:
      - ./backend/data:/app/data
      - ./backend/temp_uploads:/app/temp_uploads
      - ./backend/generated_pdfs:/app/generated_pdfs
    depends_on:
      - chromadb
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://tu-dominio.com}
    expose:
      - "80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  chromadb:
    image: chromadb/chroma:latest
    expose:
      - "8001"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_HTTP_PORT=8001
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chromadb_data: