version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - DEBUG=False
    depends_on:
      - chromadb
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://tu-dominio.com
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  chromadb_data: